[package]
name = "microworlds-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "app"
path = "src/main.rs"

[features]
performance = []

[dependencies]
eframe = "0.26.2"
image = "0.25.0"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
rfd = "0.14.0"
